name: Run Kiritori Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install atproto  

    - name: Run the script
      env:
        BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
      run: python kiritori.py  
